name: qnn
channels:
  - pytorch
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - gurobi
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - python-dotenv
  - nbconvert
  - pytest
  - pip
  - pip:
    - nbconvert[webpdf]
    - -e .[dev]
